// Code generated by protoc-gen-go. DO NOT EDIT.
// source: loki.proto

package loki

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushRequest struct {
	Streams              []*StreamAdapter `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3b449635ad5185e, []int{0}
}

func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (m *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(m, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetStreams() []*StreamAdapter {
	if m != nil {
		return m.Streams
	}
	return nil
}

type StreamAdapter struct {
	Labels  string          `protobuf:"bytes,1,opt,name=labels,proto3" json:"labels,omitempty"`
	Entries []*EntryAdapter `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	// hash contains the original hash of the stream.
	Hash                 uint64   `protobuf:"varint,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamAdapter) Reset()         { *m = StreamAdapter{} }
func (m *StreamAdapter) String() string { return proto.CompactTextString(m) }
func (*StreamAdapter) ProtoMessage()    {}
func (*StreamAdapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3b449635ad5185e, []int{1}
}

func (m *StreamAdapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamAdapter.Unmarshal(m, b)
}
func (m *StreamAdapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamAdapter.Marshal(b, m, deterministic)
}
func (m *StreamAdapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamAdapter.Merge(m, src)
}
func (m *StreamAdapter) XXX_Size() int {
	return xxx_messageInfo_StreamAdapter.Size(m)
}
func (m *StreamAdapter) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamAdapter.DiscardUnknown(m)
}

var xxx_messageInfo_StreamAdapter proto.InternalMessageInfo

func (m *StreamAdapter) GetLabels() string {
	if m != nil {
		return m.Labels
	}
	return ""
}

func (m *StreamAdapter) GetEntries() []*EntryAdapter {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *StreamAdapter) GetHash() uint64 {
	if m != nil {
		return m.Hash
	}
	return 0
}

type EntryAdapter struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Line                 string               `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EntryAdapter) Reset()         { *m = EntryAdapter{} }
func (m *EntryAdapter) String() string { return proto.CompactTextString(m) }
func (*EntryAdapter) ProtoMessage()    {}
func (*EntryAdapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3b449635ad5185e, []int{2}
}

func (m *EntryAdapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryAdapter.Unmarshal(m, b)
}
func (m *EntryAdapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryAdapter.Marshal(b, m, deterministic)
}
func (m *EntryAdapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryAdapter.Merge(m, src)
}
func (m *EntryAdapter) XXX_Size() int {
	return xxx_messageInfo_EntryAdapter.Size(m)
}
func (m *EntryAdapter) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryAdapter.DiscardUnknown(m)
}

var xxx_messageInfo_EntryAdapter proto.InternalMessageInfo

func (m *EntryAdapter) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *EntryAdapter) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func init() {
	proto.RegisterType((*PushRequest)(nil), "loki.PushRequest")
	proto.RegisterType((*StreamAdapter)(nil), "loki.StreamAdapter")
	proto.RegisterType((*EntryAdapter)(nil), "loki.EntryAdapter")
}

func init() { proto.RegisterFile("loki.proto", fileDescriptor_a3b449635ad5185e) }

var fileDescriptor_a3b449635ad5185e = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0x4d, 0x4e, 0xf3, 0x30,
	0x14, 0xfc, 0xdc, 0xe6, 0x6b, 0xe9, 0x2b, 0x3f, 0x92, 0x11, 0x52, 0xa8, 0x90, 0x5c, 0x65, 0xd5,
	0x4d, 0x5d, 0xa9, 0xac, 0x59, 0x10, 0x81, 0xc4, 0x12, 0xb9, 0x5c, 0x20, 0x01, 0x93, 0x44, 0x24,
	0x75, 0x88, 0x1d, 0x24, 0x0e, 0x81, 0xc4, 0xb1, 0x38, 0x03, 0x0b, 0xb3, 0xcf, 0x29, 0x50, 0x5e,
	0x62, 0x0a, 0x9b, 0x64, 0xde, 0x68, 0xde, 0xcc, 0xf3, 0x00, 0xe4, 0xea, 0x29, 0xe3, 0x65, 0xa5,
	0x8c, 0xa2, 0x5e, 0x8b, 0x67, 0x2c, 0x51, 0x2a, 0xc9, 0xe5, 0x0a, 0xb9, 0xb8, 0x7e, 0x5c, 0x99,
	0xac, 0x90, 0xda, 0x44, 0x45, 0xd9, 0xc9, 0x66, 0xcb, 0x24, 0x33, 0x69, 0x1d, 0xf3, 0x7b, 0x55,
	0xac, 0x12, 0x95, 0xa8, 0x9d, 0xb2, 0x9d, 0x70, 0x40, 0xd4, 0xc9, 0x83, 0x0d, 0x4c, 0x6f, 0x6b,
	0x9d, 0x0a, 0xf9, 0x5c, 0x4b, 0x6d, 0xe8, 0x15, 0x8c, 0xb5, 0xa9, 0x64, 0x54, 0x68, 0x9f, 0xcc,
	0x87, 0x8b, 0xe9, 0xfa, 0x98, 0xe3, 0x09, 0x1b, 0x24, 0x2f, 0x1f, 0xa2, 0xd2, 0xc8, 0x2a, 0x3c,
	0xf9, 0xb4, 0x6c, 0xd4, 0x51, 0x8d, 0x65, 0x6e, 0x43, 0x38, 0x10, 0xbc, 0x11, 0x38, 0xf8, 0xb3,
	0x41, 0x03, 0x18, 0xe5, 0x51, 0x2c, 0xf3, 0xd6, 0x96, 0x2c, 0x26, 0x21, 0x34, 0x96, 0xf5, 0x8c,
	0xe8, 0xff, 0xf4, 0x02, 0xc6, 0x72, 0x6b, 0xaa, 0x4c, 0x6a, 0x7f, 0x80, 0xd9, 0xb4, 0xcb, 0xbe,
	0xde, 0x9a, 0xea, 0xd5, 0x45, 0x1f, 0x7d, 0x58, 0xf6, 0xaf, 0x0d, 0xed, 0xa5, 0xc2, 0x01, 0x7a,
	0x0a, 0x5e, 0x1a, 0xe9, 0xd4, 0x1f, 0xce, 0xc9, 0xc2, 0x0b, 0xff, 0x37, 0x96, 0x91, 0xa5, 0x40,
	0x2a, 0x78, 0x81, 0xfd, 0xdf, 0x26, 0xf4, 0x06, 0x26, 0x3f, 0xb5, 0xe1, 0x41, 0xd3, 0xf5, 0x8c,
	0x77, 0xc5, 0x72, 0x57, 0x17, 0xbf, 0x73, 0x8a, 0xf0, 0xb0, 0xcf, 0x1c, 0x18, 0xfd, 0xfe, 0xc5,
	0x88, 0xd8, 0x2d, 0xd3, 0x33, 0xf0, 0xf2, 0x6c, 0x2b, 0xfd, 0x01, 0xbe, 0x6a, 0xaf, 0xb1, 0x0c,
	0x67, 0x81, 0xdf, 0x78, 0x84, 0x66, 0xe7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x60, 0x48, 0xbb,
	0xb6, 0xc7, 0x01, 0x00, 0x00,
}
